package finger.print.atm;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vishal
 */
public class TransactionWindow extends javax.swing.JFrame {

    /**
     * Creates new form TransactionWindow
     */
    public TransactionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdraw = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        getTransactionDetails = new javax.swing.JLabel();
        updateInfo = new javax.swing.JLabel();
        checkBalance = new javax.swing.JLabel();
        changePin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        withdraw.setText("Withdraw");
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
        });
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 160, -1, -1));

        deposit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deposit.setText("Deposit");
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositMouseClicked(evt);
            }
        });
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 217, -1, -1));

        getTransactionDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getTransactionDetails.setText("Get Transaction Details");
        getTransactionDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getTransactionDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(getTransactionDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 160, -1, -1));

        updateInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateInfo.setText("Change Mobile Number");
        updateInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateInfoMouseClicked(evt);
            }
        });
        getContentPane().add(updateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 217, -1, -1));

        checkBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBalance.setText("Check Balance");
        checkBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBalanceMouseClicked(evt);
            }
        });
        getContentPane().add(checkBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 284, -1, -1));

        changePin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changePin.setText("Change Pin");
        changePin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePinMouseClicked(evt);
            }
        });
        getContentPane().add(changePin, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 284, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Select any one transaction : ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 92, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        // TODO add your handling code here:
        new Withdraw().setVisible(true);
        dispose();
    }//GEN-LAST:event_withdrawMouseClicked

    private void depositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseClicked
        // TODO add your handling code here:
        new Deposit().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_depositMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void changePinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePinMouseClicked
        // TODO add your handling code here:
        new ChangePin().setVisible(true);
        dispose();
    }//GEN-LAST:event_changePinMouseClicked

    private void checkBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBalanceMouseClicked
        // TODO add your handling code here:
        //new CheckBalance().setVisible(true);
        //dispose();
        String CardNo=LogIn.Card_No;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","root");
            PreparedStatement   st=connection.prepareStatement("select balance from account where id=?");
            st.setString(1,CardNo);
            ResultSet rs=st.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Your Current Balance is : "+rs.getFloat(1)); 
            }
        }
        catch(Exception ex){}

    }//GEN-LAST:event_checkBalanceMouseClicked

    private void updateInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInfoMouseClicked
        // TODO add your handling code here:
        new UpdateMobile().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateInfoMouseClicked

    private void getTransactionDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getTransactionDetailsMouseClicked
        // TODO add your handling code here:
        new GetTransactionDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_getTransactionDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePin;
    private javax.swing.JLabel checkBalance;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel getTransactionDetails;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel updateInfo;
    private javax.swing.JLabel withdraw;
    // End of variables declaration//GEN-END:variables
}
